# Generated by Django 3.1.3 on 2020-11-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_author_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='user_name',
            field=models.CharField(default='null', max_length=256, verbose_name='Имя'),
        ),
        migrations.AlterUniqueTogether(
            name='answerlikes',
            unique_together={('answer', 'author')},
        ),
        migrations.AlterUniqueTogether(
            name='questionlikes',
            unique_together={('question', 'author')},
        ),
    ]
