# Generated by Django 3.1.3 on 2020-12-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201130_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(default='askсats/static/images/test.jpg', upload_to='avatar/%Y/%m/%d/', verbose_name='avatar'),
        ),
    ]
