# Generated by Django 3.1.3 on 2020-11-17 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201117_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Юзер', 'verbose_name_plural': 'Юзеры'},
        ),
    ]
