# Generated by Django 3.1.3 on 2020-12-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201209_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(default='static/images/test.jpg', upload_to='avatar/%Y/%m/%d/', verbose_name='avatar'),
        ),
    ]
