# Generated by Django 3.1.3 on 2020-12-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201209_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(default='images/profile.jpg', upload_to='avatar/%Y/%m/%d/', verbose_name='avatar'),
        ),
    ]
