# Generated by Django 3.1.3 on 2020-11-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201117_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identificator',
            field=models.IntegerField(default=0, verbose_name='id юзера'),
        ),
    ]
