# Generated by Django 3.1.3 on 2020-12-18 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201211_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerlikes',
            old_name='dislike',
            new_name='vote',
        ),
        migrations.RenameField(
            model_name='questionlikes',
            old_name='dislike',
            new_name='vote',
        ),
        migrations.RemoveField(
            model_name='answerlikes',
            name='like',
        ),
        migrations.RemoveField(
            model_name='questionlikes',
            name='like',
        ),
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(default='test.jpeg', upload_to='avatar/%Y/%m/%d/', verbose_name='avatar'),
        ),
    ]
