# Generated by Django 3.1.3 on 2020-11-17 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20201117_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionlikes',
            options={'verbose_name': 'Лайк на вопрос', 'verbose_name_plural': 'Лайки на вопросы'},
        ),
        migrations.RemoveField(
            model_name='questionlikes',
            name='answer',
        ),
        migrations.AddField(
            model_name='questionlikes',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.question', verbose_name='Вопрос'),
        ),
        migrations.CreateModel(
            name='AnswerLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.answer', verbose_name='Ответ')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Лайк на ответ',
                'verbose_name_plural': 'Лайки на ответы',
            },
        ),
    ]
